# docker-compose.yml
# https://docs.docker.com/compose/compose-file/compose-file-v3/
version: "3.8"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${COMPOSE_PROJECT_NAME:?err}
    container_name: ${COMPOSE_PROJECT_NAME:?err}_db
    ports:
      - 1433:1433
    volumes:
      - mssql_data:/var/opt/mssql/data
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#environment
    environment:
      # List of all SQL Server environment variables:
      # https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables?view=sql-server-ver15#environment-variables
      - ACCEPT_EULA=Y
      - MSSQL_PID=RAWRS
      - MSSQL_SA_PASSWORD=rawrs123
      - MSSQL_DATA_DIR=/var/opt/mssql/data
# Create name volumes managed by Docker to not lose data when remove a container.
# https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes
volumes:
  mssql_data:
networks:
  compose_network: